//! Contracts for automatic cross-device input verification and stress tests.
//!
//! The report deliberately keeps sender and receiver timestamps separate. A
//! monotonic duration is only calculated on the initiating daemon, while the
//! target event timestamp is retained as target-local evidence.

use serde::{Deserialize, Serialize};

use crate::{DeviceId, EndpointEvent, EndpointEventId, EndpointEventKind, EndpointInjectError};

pub const CROSS_DEVICE_MAX_SAMPLES: u32 = 10_000;
pub const CROSS_DEVICE_MAX_DURATION_MS: u64 = 60_000;
pub const CROSS_DEVICE_MAX_INTERVAL_MS: u64 = 60_000;
pub const CROSS_DEVICE_MAX_TIMEOUT_MS: u64 = 10_000;
pub const CROSS_DEVICE_REPORT_SAMPLE_LIMIT: usize = 256;

fn default_sample_count() -> u32 {
    20
}

fn default_timeout_ms() -> u64 {
    1_000
}

fn default_step() -> i32 {
    1
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum CrossDeviceTestKind {
    MouseMove,
    KeyboardShift,
}

impl Default for CrossDeviceTestKind {
    fn default() -> Self {
        Self::MouseMove
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct CrossDeviceTestRequest {
    /// When omitted, the daemon selects the first currently connected peer.
    #[serde(default)]
    pub device_id: Option<DeviceId>,
    #[serde(default)]
    pub kind: CrossDeviceTestKind,
    #[serde(default = "default_sample_count")]
    pub sample_count: u32,
    /// A non-zero duration enables continuous stress mode. The daemon still
    /// applies a hard upper bound and checks cancellation between samples.
    #[serde(default)]
    pub duration_ms: u64,
    #[serde(default)]
    pub interval_ms: u64,
    #[serde(default = "default_timeout_ms")]
    pub timeout_ms: u64,
    #[serde(default)]
    pub start_x: i32,
    #[serde(default)]
    pub start_y: i32,
    #[serde(default = "default_step")]
    pub step_x: i32,
    #[serde(default = "default_step")]
    pub step_y: i32,
}

impl Default for CrossDeviceTestRequest {
    fn default() -> Self {
        Self {
            device_id: None,
            kind: CrossDeviceTestKind::default(),
            sample_count: default_sample_count(),
            duration_ms: 0,
            interval_ms: 0,
            timeout_ms: default_timeout_ms(),
            start_x: 0,
            start_y: 0,
            step_x: default_step(),
            step_y: default_step(),
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum CrossDeviceTestRunState {
    Idle,
    Running,
    Completed,
    Stopped,
    Failed,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct CrossDeviceTestSample {
    pub index: u32,
    pub correlation_id: String,
    pub event_kind: EndpointEventKind,
    #[serde(default)]
    pub position_x: Option<i32>,
    #[serde(default)]
    pub position_y: Option<i32>,
    #[serde(default)]
    pub display_id: Option<String>,
    /// Wall-clock timestamp used for cross-host log correlation only.
    pub sent_timestamp_ms: u64,
    #[serde(default)]
    pub response_timestamp_ms: Option<u64>,
    /// Timestamp generated by the target endpoint's local clock.
    #[serde(default)]
    pub remote_event_timestamp_ms: Option<u64>,
    /// Same-process monotonic request-to-response duration.
    #[serde(default)]
    pub elapsed_us: Option<u64>,
    pub accepted: bool,
    pub observed: bool,
    #[serde(default)]
    pub remote_event_id: Option<EndpointEventId>,
    /// The target event carrying the actual payload, position and correlation.
    #[serde(default)]
    pub event: Option<EndpointEvent>,
    #[serde(default)]
    pub error: Option<EndpointInjectError>,
}

#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct CrossDeviceTestMetrics {
    pub requested: u32,
    pub sent: u32,
    pub accepted: u32,
    pub observed: u32,
    pub failed: u32,
    pub timed_out: u32,
    pub cancelled: u32,
    pub p50_us: Option<u64>,
    pub p95_us: Option<u64>,
    pub p99_us: Option<u64>,
    pub max_us: Option<u64>,
    /// Throughput in events/second multiplied by 1000, avoiding floating point
    /// values in the IPC contract.
    pub throughput_per_second_milli: Option<u64>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct CrossDeviceTestReport {
    pub test_id: String,
    #[serde(default)]
    pub target_device_id: Option<DeviceId>,
    pub kind: CrossDeviceTestKind,
    pub state: CrossDeviceTestRunState,
    pub started_timestamp_ms: u64,
    #[serde(default)]
    pub finished_timestamp_ms: Option<u64>,
    pub duration_ms: u64,
    pub metrics: CrossDeviceTestMetrics,
    /// Bounded tail of samples; aggregate metrics cover the full run.
    pub samples: Vec<CrossDeviceTestSample>,
    #[serde(default)]
    pub error: Option<String>,
}

#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct CrossDeviceTestStatusSnapshot {
    pub active: bool,
    #[serde(default)]
    pub report: Option<CrossDeviceTestReport>,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn request_defaults_to_bounded_mouse_probe() {
        let request = CrossDeviceTestRequest::default();
        assert_eq!(request.kind, CrossDeviceTestKind::MouseMove);
        assert_eq!(request.sample_count, 20);
        assert_eq!(request.timeout_ms, 1_000);
    }

    #[test]
    fn new_fields_are_optional_for_legacy_inject_results() {
        let json = r#"{
            "correlation_id":"legacy",
            "target":"Local",
            "accepted":true,
            "backend_kind":null,
            "health":"Healthy",
            "elapsed_ms":1,
            "loopback_event_id":1,
            "error":null
        }"#;
        let result: crate::EndpointInjectResult = serde_json::from_str(json).unwrap();
        assert!(result.observed_event.is_none());
    }
}
