#pragma once

#if defined(_KERNEL_MODE) || defined(_NTDDK_) || defined(_WDMDDK_)
#include <ntddk.h>
#else
#include <windows.h>
#include <winioctl.h>
#endif

#define RSHARE_STATIC_ASSERT_JOIN2(a, b) a##b
#define RSHARE_STATIC_ASSERT_JOIN(a, b) RSHARE_STATIC_ASSERT_JOIN2(a, b)
#define RSHARE_STATIC_ASSERT(e) \
    typedef char RSHARE_STATIC_ASSERT_JOIN(rshare_static_assert_, __LINE__)[(e) ? 1 : -1]

#define RSHARE_DRIVER_ABI 1
#define RSHARE_NT_DEVICE_NAME L"\\Device\\RShareInputControl"
#define RSHARE_DOS_DEVICE_NAME L"\\DosDevices\\RShareInputControl"
#define RSHARE_VHID_NT_DEVICE_NAME L"\\Device\\RShareVirtualHidControl"
#define RSHARE_VHID_DOS_DEVICE_NAME L"\\DosDevices\\RShareVirtualHidControl"
#define RSHARE_VDISPLAY_DOS_DEVICE_NAME L"\\\\.\\RShareVirtualDisplayControl"

#define RSHARE_CAP_FILTER_EVENTS 0x00000001u
#define RSHARE_CAP_VIRTUAL_KEYBOARD 0x00000002u
#define RSHARE_CAP_VIRTUAL_MOUSE 0x00000004u
#define RSHARE_CAP_VIRTUAL_GAMEPAD_SCAFFOLD 0x00000008u
#define RSHARE_CAP_VIRTUAL_DISPLAY 0x00000010u
#define RSHARE_CAP_FILTER_SEMANTIC_QUEUE 0x00000020u
#define RSHARE_CAP_WAIT_EVENT 0x00000040u

#define RSHARE_FILTER_EVENT_FORMAT_VERSION 2u
#define RSHARE_FILTER_STATS_VERSION 2u
#define RSHARE_FILTER_WAIT_STATE_VERSION 1u

#define RSHARE_VDISPLAY_ACTIVITY_REMOVED 0u
#define RSHARE_VDISPLAY_ACTIVITY_ACTIVE 1u
#define RSHARE_VDISPLAY_ACTIVITY_PENDING 2u

#define RSHARE_SOURCE_HARDWARE 1u
#define RSHARE_SOURCE_INJECTED_LOOPBACK 2u
#define RSHARE_SOURCE_DRIVER_TEST 3u
#define RSHARE_SOURCE_VIRTUAL_DEVICE 4u

#define RSHARE_DEVICE_KEYBOARD 1u
#define RSHARE_DEVICE_MOUSE 2u
#define RSHARE_DEVICE_GAMEPAD 3u

#define RSHARE_EVENT_KEY 1u
#define RSHARE_EVENT_MOUSE_MOVE 2u
#define RSHARE_EVENT_MOUSE_BUTTON 3u
#define RSHARE_EVENT_MOUSE_WHEEL 4u
#define RSHARE_EVENT_SYNTHETIC 5u
#define RSHARE_EVENT_RELIABLE_OVERFLOW 6u

#define RSHARE_REPORT_KEYBOARD 1u
#define RSHARE_REPORT_MOUSE_MOVE 2u
#define RSHARE_REPORT_MOUSE_BUTTON 3u
#define RSHARE_REPORT_MOUSE_WHEEL 4u

#define IOCTL_RSHARE_QUERY_VERSION \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x801, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_RSHARE_QUERY_CAPABILITIES \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x802, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_RSHARE_READ_EVENT \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x803, METHOD_BUFFERED, FILE_READ_DATA)
#define IOCTL_RSHARE_INJECT_REPORT \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x804, METHOD_BUFFERED, FILE_WRITE_DATA)
#define IOCTL_RSHARE_EMIT_TEST_PACKET \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x805, METHOD_BUFFERED, FILE_WRITE_DATA)
#define IOCTL_RSHARE_QUERY_STATS \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x806, METHOD_BUFFERED, FILE_READ_DATA)
#define IOCTL_RSHARE_QUERY_FILTER_STATS_V2 \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x807, METHOD_BUFFERED, FILE_READ_DATA)
#define IOCTL_RSHARE_WAIT_EVENT \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x808, METHOD_BUFFERED, FILE_READ_DATA)
#define IOCTL_RSHARE_QUERY_FILTER_WAIT_STATE \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x809, METHOD_BUFFERED, FILE_READ_DATA)
#define IOCTL_RSHARE_VDISPLAY_QUERY_STATE \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x811, METHOD_BUFFERED, FILE_READ_DATA)
#define IOCTL_RSHARE_VDISPLAY_CREATE \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x812, METHOD_BUFFERED, FILE_WRITE_DATA)
#define IOCTL_RSHARE_VDISPLAY_REMOVE \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x813, METHOD_BUFFERED, FILE_WRITE_DATA)

typedef struct _RSHARE_DRIVER_VERSION {
    USHORT Major;
    USHORT Minor;
    USHORT Patch;
    USHORT Abi;
} RSHARE_DRIVER_VERSION, *PRSHARE_DRIVER_VERSION;

typedef struct _RSHARE_DRIVER_CAPABILITIES {
    USHORT Abi;
    ULONG Flags;
    ULONG MaxEventSize;
    ULONG Reserved;
} RSHARE_DRIVER_CAPABILITIES, *PRSHARE_DRIVER_CAPABILITIES;

typedef struct _RSHARE_DRIVER_EVENT {
    USHORT Abi;
    USHORT Source;
    ULONG DeviceKind;
    ULONG EventKind;
    ULONG Flags;
    ULONGLONG DeviceId;
    ULONGLONG DeviceInstanceHash;
    LONG Value0;
    LONG Value1;
    LONG Value2;
    ULONGLONG TimestampUs;
} RSHARE_DRIVER_EVENT, *PRSHARE_DRIVER_EVENT;

typedef struct _RSHARE_DRIVER_STATS {
    USHORT Abi;
    USHORT Reserved0;
    ULONG QueueCapacity;
    ULONG QueueDepth;
    ULONGLONG QueuedEventCount;
    ULONGLONG DroppedEventCount;
    ULONGLONG KeyboardConnectCount;
    ULONGLONG MouseConnectCount;
    ULONGLONG KeyboardEventCount;
    ULONGLONG MouseEventCount;
} RSHARE_DRIVER_STATS, *PRSHARE_DRIVER_STATS;

#define RSHARE_DRIVER_STATS_SIZE 64u
RSHARE_STATIC_ASSERT(sizeof(RSHARE_DRIVER_STATS) == RSHARE_DRIVER_STATS_SIZE);

typedef struct _RSHARE_FILTER_STATS_V2 {
    USHORT Abi;
    USHORT Version;
    ULONG StructSize;
    ULONG QueueCapacity;
    ULONG QueueDepth;
    ULONGLONG QueuedEventCount;
    ULONGLONG RealtimeCoalescedCount;
    ULONGLONG RealtimeDroppedCount;
    ULONGLONG ReliableOverflowCount;
    ULONGLONG KeyboardConnectCount;
    ULONGLONG MouseConnectCount;
    ULONGLONG KeyboardEventCount;
    ULONGLONG MouseEventCount;
} RSHARE_FILTER_STATS_V2, *PRSHARE_FILTER_STATS_V2;

#define RSHARE_FILTER_STATS_V2_SIZE 80u
RSHARE_STATIC_ASSERT(sizeof(RSHARE_FILTER_STATS_V2) == RSHARE_FILTER_STATS_V2_SIZE);

typedef struct _RSHARE_FILTER_WAIT_STATE {
    USHORT Abi;
    USHORT Version;
    ULONG StructSize;
    ULONG PendingWaiters;
    ULONG Reserved;
} RSHARE_FILTER_WAIT_STATE, *PRSHARE_FILTER_WAIT_STATE;

#define RSHARE_FILTER_WAIT_STATE_SIZE 16u
RSHARE_STATIC_ASSERT(
    sizeof(RSHARE_FILTER_WAIT_STATE) == RSHARE_FILTER_WAIT_STATE_SIZE);

typedef struct _RSHARE_INJECT_REPORT {
    ULONG ReportKind;
    LONG Value0;
    LONG Value1;
    LONG Value2;
    ULONG Flags;
} RSHARE_INJECT_REPORT, *PRSHARE_INJECT_REPORT;

typedef struct _RSHARE_TEST_PACKET {
    ULONG DeviceKind;
    ULONG EventKind;
    LONG Value0;
    LONG Value1;
    LONG Value2;
} RSHARE_TEST_PACKET, *PRSHARE_TEST_PACKET;

typedef struct _RSHARE_VDISPLAY_REQUEST {
    ULONG Width;
    ULONG Height;
    ULONG RefreshRateMillihz;
    ULONG Flags;
} RSHARE_VDISPLAY_REQUEST, *PRSHARE_VDISPLAY_REQUEST;

typedef struct _RSHARE_VDISPLAY_STATE {
    USHORT Abi;
    USHORT Active;
    ULONG Width;
    ULONG Height;
    ULONG RefreshRateMillihz;
    ULONG ConnectorIndex;
} RSHARE_VDISPLAY_STATE, *PRSHARE_VDISPLAY_STATE;
